// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqcywblayontdqguynwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xY3l3YmxheW9udGRxZ3V5bndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjkxMDMsImV4cCI6MjA2MTE0NTEwM30.iZGCoqo_zmwRIPNMjSesAcpGY0wSCymenVlDfef54dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);